### ISSUE TITLE
global object __universal__'s context is managed for each request?

### ISSUE THREAD

**Issue by dehypnosis** [creeperyang/iso-morphic-style-loader#1]
Thank you for your hard job!

Because this library now handle style lists in the global context,

I'm just curious about how style lists are managed per each request context on the server.

What about the request critial situation,  server get so many request for the short period of time?

will it not generate too much style or not miss some style?

thanks in advance.!

**Comment by creeperyang** [comment]
Good question!

Since I just use it in development env, each request doesn't has its own context currently.

I will check how to improve it. And any suggestion / pr is welcome.

**Comment by creeperyang** [comment]
See 19654582ebc06b688490640f374aa3322cf1f11c
